### ISSUE TITLE
[NGE] AI ignores height difference

### ISSUE THREAD

**Issue by Undercova** [ProjectSWGCore/Holocore#136]
AI only cares about x and z distance to you (2D). Stand 100m above a red NPC and it will start to attack you and "climb" to you in little warp steps

**Comment by madsboddum** [comment]
I think we need to be able to read terrain height (Y) given X and Z coordinates in order to fix this. It's likely that the NPCs are not having their Y coordinate set at all right now.
Once we can do that, then this method: `com.projectswg.holocore.resources.support.objects.swg.custom.AIObject#checkAwareAttack`
should have distance check changed from
```java
double distance = getLocation().flatDistanceTo(player.getLocation()); // 2D
```
to
```java
double distance = getLocation().distanceTo(player.getLocation()); // 3D
```

What do you think @Obique?
